spring:
  application:
    name: mask-config
  cloud:
    config:
      server:
        git:
          uri: https://github.com/huangqiaofei/spring-cloud-mask/
          search-paths: config-qiao
          # 如果代码仓库是公开的，则不需要设置用户名和密码
          username:
          password:
server:
  port: 8088
